services:
  - type: web
    name: wahis-proxy-service
    env: python
    plan: free
    
    # === THAY ĐỔI QUAN TRỌNG ===
    
    # 1. buildCommand bây giờ chỉ cần thực thi file build.sh
    buildCommand: "./build.sh"
    
    # 2. Giữ nguyên startCommand
    startCommand: "gunicorn proxy_app:app"
    
    # 3. Giữ nguyên biến môi trường
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5