services:
  - type: web
    name: wahis-proxy-service
    env: python
    plan: free
    
    # === CÁC THAY ĐỔI QUAN TRỌNG NẰM Ở ĐÂY ===
    
    # 1. Thêm một "buildFilter" để chỉ định các file cần theo dõi
    buildFilter:
      paths:
      - "proxy_app.py"
      - "requirements.txt"
      
    # 2. Định nghĩa môi trường build và runtime
    runtime: native
    
    # 3. Di chuyển các lệnh build vào trong "buildCommand"
    buildCommand: |
      apt-get update && apt-get install -y google-chrome-stable libnss3 libxss1
      pip install -r requirements.txt
      
    # 4. Giữ nguyên startCommand
    startCommand: gunicorn proxy_app:app
    
    # 5. Giữ nguyên biến môi trường
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5